// ==================== DADOS DOS INDICADORES DE QUALIDADE ====================
// Dados de Setembro/2025

// Array de KPIs (21 indicadores)
const kpis = [
    {
        id: "consulta_pre",
        title: "Consulta Pré-Anestésica Ambulatorial",
        value: "97%",
        goal: "≥95%",
        subtitle: "Setembro/2025",
        icon: "📋",
        barPct: 97,
        tone: "good",
    },
    {
        id: "dor_aguda",
        title: "Incidência de Dor Aguda",
        value: "4%",
        goal: "≤10%",
        subtitle: "Intraoperatório até alta",
        icon: "💊",
        barPct: 95,
        tone: "good",
    },
    {
        id: "jejum",
        title: "Abreviação do Jejum Prolongado",
        value: "42%",
        goal: "≥60%",
        subtitle: "Setembro/2025",
        icon: "🍽️",
        barPct: 70,
        tone: "warn",
    },
    {
        id: "pcr",
        title: "Parada Cardiorrespiratória",
        value: "0,001%",
        goal: "≤1/10.000",
        subtitle: "Indução até alta anestésica",
        icon: "❤️",
        barPct: 99,
        tone: "good",
    },
    {
        id: "mudanca_tecnica",
        title: "Mudança de Técnica Anestésica",
        value: "0%",
        goal: "<5%",
        subtitle: "Setembro/2025",
        icon: "✅",
        barPct: 100,
        tone: "good",
    },
    {
        id: "uti_nao_planejada",
        title: "UTI Sem Planejamento Prévio",
        value: "0,1%",
        goal: "≤0,3%",
        subtitle: "Eventos anestésicos",
        icon: "🏥",
        barPct: 95,
        tone: "good",
    },
    {
        id: "controle_glicemico",
        title: "Controle Glicêmico Perioperatório",
        value: "82%",
        goal: "≥90%",
        subtitle: "Setembro/2025",
        icon: "📊",
        barPct: 91,
        tone: "warn",
    },
    {
        id: "saidas_sem_eventos",
        title: "Saídas Sem Eventos Anestésicos",
        value: "90%",
        goal: ">90%",
        subtitle: "Setembro/2025",
        icon: "🛡️",
        barPct: 90,
        tone: "good",
    },
    {
        id: "mortalidade",
        title: "Mortalidade Associada à Anestesia",
        value: "0%",
        goal: "Meta zero",
        subtitle: "48h e 30 dias",
        icon: "🏆",
        barPct: 100,
        tone: "good",
    },
    {
        id: "estratificacao_risco",
        title: "Estratificação de Risco Anestésico",
        value: "100%",
        goal: "≥98-100%",
        subtitle: "Setembro/2025",
        icon: "📈",
        barPct: 100,
        tone: "good",
    },
    {
        id: "via_aerea",
        title: "Via Aérea Difícil Não Identificada",
        value: "0,6%",
        goal: "≤2%",
        subtitle: "Setembro/2025",
        icon: "🫁",
        barPct: 97,
        tone: "good",
    },
    {
        id: "nausea_vomito",
        title: "Náusea e Vômito Pós-Operatório",
        value: "4%",
        goal: "≤20%",
        subtitle: "Setembro/2025",
        icon: "🤢",
        barPct: 96,
        tone: "good",
    },
    {
        id: "intoxicacao_al",
        title: "Protocolo Intoxicação Anestésicos",
        value: "100%",
        goal: "≥90%",
        subtitle: "Efetividade do manejo",
        icon: "💉",
        barPct: 100,
        tone: "good",
    },
    {
        id: "atb_timing",
        title: "Antibioticoprofilaxia - Timing",
        value: "97%",
        goal: "≥95%",
        subtitle: "Setembro/2025",
        icon: "⏱️",
        barPct: 97,
        tone: "good",
    },
    {
        id: "atb_droga",
        title: "Antibioticoprofilaxia - Droga Correta",
        value: "100%",
        goal: "≥95%",
        subtitle: "Setembro/2025",
        icon: "💊",
        barPct: 100,
        tone: "good",
    },
    {
        id: "atb_repique",
        title: "Antibioticoprofilaxia - Repique",
        value: "100%",
        goal: "≥95%",
        subtitle: "Setembro/2025",
        icon: "🔄",
        barPct: 100,
        tone: "good",
    },
    {
        id: "profilaxia_cirurgica",
        title: "Profilaxia Antimicrobiana Cirúrgica",
        value: "99%",
        goal: "≥95%",
        subtitle: "Setembro/2025",
        icon: "✅",
        barPct: 99,
        tone: "good",
    },
    {
        id: "cefaleia_puncao",
        title: "Prevenção Cefaleia Pós-Punção",
        value: "100%",
        goal: "≥95%",
        subtitle: "Setembro/2025",
        icon: "🧠",
        barPct: 100,
        tone: "good",
    },
    {
        id: "hipotermia",
        title: "Hipotermia Não Intencional",
        value: "0,5%",
        goal: "≤5%",
        subtitle: "Setembro/2025",
        icon: "🌡️",
        barPct: 97,
        tone: "good",
    },
    {
        id: "protocolos_seguranca",
        title: "Adesão Protocolos de Segurança",
        value: "94%",
        goal: "95%",
        subtitle: "Setembro/2025",
        icon: "🔒",
        barPct: 94,
        tone: "ok",
    },
    {
        id: "protocolos_clinicos",
        title: "Adesão Protocolos Clínico-Assistenciais",
        value: "84%",
        goal: "95%",
        subtitle: "Setembro/2025",
        icon: "📋",
        barPct: 84,
        tone: "warn",
    },
];

// Array de grupos de documentos (6 grupos)
const docGroups = [
    {
        id: "infeccao",
        title: "Taxa de Infecção",
        description: "Indicadores e relatórios de IRAS e hemorragia",
        icon: "🦠",
        backgroundColor: "#DC2626",
        onclick: "showTaxaInfeccao()",
    },
    {
        id: "adesao_protocolos",
        title: "Adesão aos Protocolos",
        description: "Time Out, SBAR, psicobox, antibiótico profilático",
        icon: "✅",
        backgroundColor: "#059669",
        onclick: "showAdesaoProtocolos()",
    },
    {
        id: "eventos_adversos",
        title: "Eventos Adversos",
        description: "Classificação por dano, causas raiz e planos de ação",
        icon: "⚠️",
        backgroundColor: "#EA580C",
        onclick: "showEventosAdversos()",
    },
    {
        id: "satisfacao_paciente",
        title: "Satisfação do Paciente",
        description: "Pesquisas e avaliações de segurança percebida",
        icon: "⭐",
        backgroundColor: "#7C3AED",
        onclick: "showSatisfacaoPaciente()",
    },
    {
        id: "tempo_atendimento",
        title: "Tempo de Atendimento",
        description: "Tempo-resposta a eventos críticos e UTI",
        icon: "⏱️",
        backgroundColor: "#0891B2",
        onclick: "showTempoAtendimento()",
    },
    {
        id: "seguranca_medicamentosa",
        title: "Segurança Medicamentosa",
        description: "Rastreabilidade, RAM e profilaxia antibiótica",
        icon: "💊",
        backgroundColor: "#DB2777",
        onclick: "showSegurancaMedicamentosa()",
    },
];
