-- ============================================================================
-- Revisão das traduções dos 3 artigos da curadoria (pedido do dono 16/08:
-- "tradução incorreta e incompatível com a gramática").
--
-- O artigo da BJA veio da tradução AUTOMÁTICA do cron (translate-pending) com
-- erros graves: "Pam"/"MAP" misturados sem definir a sigla, "a causalidade
-- dos ECRs" (o original é causalidade A PARTIR de ECRs), "entre OS grupos",
-- "outcomes" vertido como "resultados" (o termo consagrado é DESFECHOS) e o
-- abstract achatado num bloco único sem seções. Os outros dois, escritos à
-- mão em 15/08, tinham anglicismos ("placebo-controlado", "boluses") e
-- concordâncias a corrigir.
--
-- Seguro contra re-tradução: enqueue_noticia_translation() só enfileira
-- INSERT com titulo_pt nulo (trigger é AFTER INSERT; UPDATE nunca enfileira).
-- Rótulos INTRODUÇÃO/MÉTODOS/RESULTADOS/CONCLUSÕES casam com o parser de
-- abstract estruturado do NoticiaDetalhePage.
-- ============================================================================

-- 1. POISE-3 TXA em cirurgia urológica (Eur Urol)
update public.noticias set
  titulo_pt = 'Segurança e eficácia do ácido tranexâmico em cirurgia urológica: resultados do ensaio clínico internacional, randomizado e controlado por placebo POISE-3',
  resumo_pt = E'INTRODUÇÃO: O sangramento perioperatório é comum. As evidências sobre o ácido tranexâmico (TXA) em urologia permanecem limitadas e conflitantes, e as principais diretrizes urológicas não fazem recomendação sobre seu uso. Em uma análise planejada a priori, avaliamos o TXA nos pacientes do POISE-3 submetidos a cirurgia urológica.\nMÉTODOS: O POISE-3 foi um ensaio clínico randomizado internacional com pacientes submetidos a cirurgia que apresentavam fatores de risco hemorrágico e cardiovascular. Os participantes receberam TXA (bolus intravenoso de 1 g no início e no fim da cirurgia) ou placebo. O desfecho primário de eficácia foi um desfecho composto de sangramento em 30 dias (sangramento com risco de vida, sangramento maior ou sangramento em órgão crítico), e o desfecho primário de segurança foi um desfecho composto de trombose em 30 dias (lesão miocárdica após cirurgia não cardíaca [MINS], acidente vascular cerebral não hemorrágico, trombose arterial periférica ou tromboembolismo venoso proximal sintomático [TEV]).\nRESULTADOS: Entre os 1.124 participantes submetidos a cirurgia urológica (556 com TXA e 568 com placebo), 489 foram operados por via laparoscópica/robótica, 360 por via aberta, 244 por via transuretral e 31 por via percutânea. O desfecho composto de sangramento ocorreu em 45 pacientes (8,1%) com TXA e em 62 (10,9%) com placebo (hazard ratio [HR] 0,73; IC 95% 0,50–1,07). Sangramento maior ocorreu em 34 (6,1%) com TXA e em 54 (9,5%) com placebo (HR 0,63; IC 95% 0,41–0,97). O desfecho composto de segurança ocorreu em 67 (12,1%) com TXA e em 62 (10,9%) com placebo (HR 1,12; IC 95% 0,79–1,58; MINS: 62 vs 58; AVC: 2 vs 2; TEV: 3 vs 3).\nCONCLUSÕES: O TXA reduziu o sangramento maior, o que respalda seu uso perioperatório em cirurgia urológica, especialmente quando o risco de sangramento é alto.'
where doi = '10.1016/j.eururo.2026.03.019';

-- 2. Hipotensão intraoperatória — meta-análise (BJA)
update public.noticias set
  titulo_pt = 'Hipotensão intraoperatória e desfechos pós-operatórios adversos: revisão sistemática e meta-análise de ensaios clínicos randomizados',
  resumo_pt = E'INTRODUÇÃO: A hipotensão arterial intraoperatória ocorre com frequência e está associada a desfechos adversos. As evidências de causalidade provenientes de ensaios clínicos randomizados (ECRs) são escassas. Esta meta-análise teve como objetivo sintetizar as evidências de ECRs que categorizaram grupos com base em limiares de pressão arterial média (PAM), examinando o impacto sobre mortalidade, lesão renal aguda (LRA) e lesão miocárdica em pacientes submetidos a cirurgia não cardíaca.\nMÉTODOS: Foi realizada busca sistemática nas bases PubMed, Embase e Web of Science por ECRs em adultos submetidos a cirurgia não cardíaca que categorizaram os grupos com base em limiares de PAM. O objetivo primário foi examinar o efeito das diferenças de PAM alcançada sobre o desfecho primário de mortalidade por todas as causas em até 30 dias após a cirurgia. LRA, lesão miocárdica e a PAM alcançada nos braços de intervenção e de controle foram analisadas como desfechos secundários. Em cada estudo foram identificados dois grupos: um de intervenção (alvo de pressão "mais alta") e um de controle (alvo de pressão "mais baixa"). Uma análise exploratória examinou se a diferença de PAM alcançada entre os grupos modificava os resultados dos estudos.\nRESULTADOS: Nove ECRs, totalizando 14.658 pacientes, não demonstraram diferença no desfecho primário de mortalidade por todas as causas entre os grupos de intervenção e de controle (RR 1,06; IC 95% 0,77–1,45; I² = 0%). Não foram observadas diferenças nos desfechos secundários em 13 ECRs. As diferenças de PAM intraoperatória alcançada entre os grupos não se associaram aos desfechos dos estudos.\nCONCLUSÕES: PAM intraoperatória mais alta versus mais baixa não afetou a mortalidade por todas as causas em 30 dias, a LRA nem a lesão miocárdica; entretanto, apenas diferenças limitadas de pressão arterial foram de fato alcançadas entre os grupos. A estratificação pelas diferenças de pressão alcançada não alterou os resultados. Protocolo de revisão sistemática registrado no PROSPERO (CRD420251230069).'
where doi = '10.1016/j.bja.2026.05.061';

-- 3. Cateter DPIP bilateral pós-esternotomia (A&A)
update public.noticias set
  titulo_pt = 'Efeito de doses repetidas em bolus por cateteres bilaterais no plano intercostal paraesternal profundo sobre a analgesia após cirurgia cardíaca: ensaio clínico randomizado',
  resumo_pt = E'INTRODUÇÃO: A esternotomia mediana em cirurgia cardíaca está associada a dor pós-operatória significativa. Avaliamos se doses repetidas de ropivacaína em bolus, administradas por cateteres bilaterais no plano intercostal paraesternal profundo (DPIP), melhoram a analgesia após cirurgia cardíaca.\nMÉTODOS: Neste ensaio clínico randomizado e controlado por placebo, 120 pacientes adultos submetidos a cirurgia eletiva de revascularização do miocárdio ou de troca valvar foram alocados para receber doses repetidas em bolus de ropivacaína ou de soro fisiológico, por cateteres DPIP bilaterais, durante as primeiras 72 horas de pós-operatório. Pacientes, pesquisadores e equipe assistencial estavam cegados para a alocação dos grupos. O desfecho primário foi a intensidade da dor pós-operatória, avaliada pela escala visual analógica ou, nos pacientes sedados, pela escala comportamental de dor. Os desfechos secundários incluíram consumo acumulado de oxicodona, eventos adversos, sedação pós-operatória e ventilação mecânica.\nRESULTADOS: As trajetórias de dor ao longo das 72 horas de pós-operatório não diferiram entre os grupos (interação grupo × tempo: P = 0,77 em repouso e P = 1,00 em movimento). Não houve diferença estatisticamente significativa entre os grupos no consumo acumulado de opioides. Náuseas e vômitos pós-operatórios foram o evento adverso mais comum (38% do total), com maior incidência entre os pacientes de cirurgia valvar tratados com ropivacaína. Cinco pacientes apresentaram sintomas sugestivos de toxicidade sistêmica por anestésico local; todos os casos foram autolimitados. Ocorreram quatro pneumotóraces, um deles claramente relacionado à cirurgia. O cateter deslocou-se em nove pacientes.\nCONCLUSÕES: Doses repetidas de ropivacaína em bolus por cateteres DPIP não melhoraram o controle da dor pós-operatória nem reduziram o consumo de opioides em comparação com o placebo após esternotomia mediana. O uso rotineiro de cateteres DPIP após cirurgia cardíaca deve, portanto, ser evitado.'
where doi = '10.1213/ane.0000000000008211';
